# source database URL
# database URLs take the format of:
#   postgres://user:password@host:port/dbname
#
# we recommend a command which outputs a database URL
# so sensitive information is not included in this file
#
# we *highly recommend* you use sslmode=verify-full when possible
# see https://ankane.org/postgres-sslmode-explained for more info
from: localhost://alarm:alarm@192.168.0.109:5432/PlanerP?sslmode=require

# destination database URL
# to: postgres://alarm:alarm@192.168.0.109:5432/PlanerP
to: .

# exclude tables
# exclude:
#   - table1
#   - table2

# define groups
# groups:
#   group1:
#     - table1
#     - table2

# sync specific schemas
# schemas:
#   - public

# protect sensitive information
data_rules:
  email: unique_email
  phone: unique_phone
  last_name: random_letter
  birthday: random_date
  encrypted_*: null
