// This file is auto-generated by @hey-api/openapi-ts

export const ComponentSchema = {
    allOf: [
        {
            '$ref': '#/components/schemas/BaseModel'
        },
        {
            type: 'object',
            additionalProperties: false,
            properties: {
                name: {
                    type: 'string',
                    nullable: true
                },
                partNumber: {
                    type: 'string',
                    nullable: true
                },
                imageUrl: {
                    type: 'string',
                    nullable: true
                },
                apiUrl: {
                    type: 'string',
                    nullable: true
                },
                type: {
                    type: 'string',
                    nullable: true
                },
                category: {
                    type: 'string',
                    nullable: true
                },
                description: {
                    type: 'string',
                    nullable: true
                },
                price: {
                    type: 'number',
                    format: 'float'
                },
                capital: {
                    type: 'number',
                    format: 'float'
                },
                supplier: {
                    type: 'string',
                    nullable: true
                },
                supplierLink: {
                    type: 'string',
                    nullable: true
                },
                isAssembly: {
                    type: 'boolean'
                },
                stock: {
                    type: 'integer',
                    format: 'int32'
                },
                buyDate: {
                    type: 'string',
                    format: 'date-time'
                },
                storageId: {
                    type: 'integer',
                    format: 'int32',
                    nullable: true
                }
            }
        }
    ]
} as const;

export const BaseModelSchema = {
    type: 'object',
    'x-abstract': true,
    additionalProperties: false,
    properties: {
        id: {
            type: 'integer',
            format: 'int32',
            nullable: true
        }
    }
} as const;

export const CurrencySchema = {
    type: 'object',
    additionalProperties: false,
    properties: {
        time: {
            type: 'string',
            nullable: true
        },
        cube: {
            type: 'array',
            nullable: true,
            items: {
                '$ref': '#/components/schemas/CurrencyItem'
            }
        }
    }
} as const;

export const CurrencyItemSchema = {
    type: 'object',
    additionalProperties: false,
    properties: {
        currency: {
            type: 'string',
            nullable: true
        },
        rate: {
            type: 'number',
            format: 'float'
        }
    }
} as const;

export const RegisterIdentityModalSchema = {
    type: 'object',
    additionalProperties: false,
    properties: {
        userName: {
            type: 'string',
            nullable: true
        },
        email: {
            type: 'string',
            nullable: true
        },
        firstName: {
            type: 'string',
            nullable: true
        },
        lastName: {
            type: 'string',
            nullable: true
        },
        password: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const LoggerModelSchema = {
    allOf: [
        {
            '$ref': '#/components/schemas/BaseModel'
        },
        {
            type: 'object',
            additionalProperties: false,
            properties: {
                date: {
                    type: 'string',
                    format: 'date-time'
                },
                title: {
                    type: 'string',
                    nullable: true
                },
                description: {
                    type: 'string',
                    nullable: true
                },
                projectId: {
                    type: 'integer',
                    format: 'int32',
                    nullable: true
                }
            }
        }
    ]
} as const;

export const ComponentPriceHistorySchema = {
    type: 'object',
    additionalProperties: false,
    properties: {
        path: {
            type: 'string',
            nullable: true
        },
        url: {
            type: 'string',
            nullable: true
        },
        componentId: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const ProducingStepSchema = {
    allOf: [
        {
            '$ref': '#/components/schemas/BaseModel'
        },
        {
            type: 'object',
            additionalProperties: false,
            properties: {
                listStep: {
                    type: 'string',
                    nullable: true
                },
                projectId: {
                    type: 'integer',
                    format: 'int32',
                    nullable: true
                }
            }
        }
    ]
} as const;

export const ProjectSchema = {
    allOf: [
        {
            '$ref': '#/components/schemas/BaseModel'
        },
        {
            type: 'object',
            additionalProperties: false,
            properties: {
                name: {
                    type: 'string',
                    nullable: true
                },
                imageUrl: {
                    type: 'string',
                    nullable: true
                },
                createdDate: {
                    type: 'string',
                    format: 'date-time'
                },
                deadLineDate: {
                    type: 'string',
                    format: 'date-time',
                    nullable: true
                },
                lastUpdatedDate: {
                    type: 'string',
                    format: 'date-time'
                },
                finishedDate: {
                    type: 'string',
                    format: 'date-time',
                    nullable: true
                },
                sellPrice: {
                    type: 'number',
                    format: 'float',
                    nullable: true
                },
                capital: {
                    type: 'number',
                    format: 'float'
                },
                fail: {
                    type: 'boolean'
                },
                finish: {
                    type: 'boolean'
                },
                profitInPersen: {
                    type: 'number',
                    format: 'float',
                    nullable: true
                },
                description: {
                    type: 'string',
                    nullable: true
                }
            }
        }
    ]
} as const;

export const UsedComponentSchema = {
    allOf: [
        {
            '$ref': '#/components/schemas/BaseModel'
        },
        {
            type: 'object',
            additionalProperties: false,
            properties: {
                projectId: {
                    type: 'integer',
                    format: 'int32'
                },
                componentId: {
                    type: 'integer',
                    format: 'int32'
                },
                count: {
                    type: 'integer',
                    format: 'int32'
                },
                totalPrice: {
                    type: 'number',
                    format: 'double'
                }
            }
        }
    ]
} as const;

export const ResourceDocSchema = {
    allOf: [
        {
            '$ref': '#/components/schemas/BaseModel'
        },
        {
            type: 'object',
            additionalProperties: false,
            properties: {
                overview: {
                    type: 'string',
                    nullable: true
                },
                description: {
                    type: 'string',
                    nullable: true
                }
            }
        }
    ]
} as const;

export const StorageSchema = {
    allOf: [
        {
            '$ref': '#/components/schemas/BaseModel'
        },
        {
            type: 'object',
            additionalProperties: false,
            properties: {
                name: {
                    type: 'string',
                    nullable: true
                },
                location: {
                    type: 'string',
                    nullable: true
                },
                description: {
                    type: 'string',
                    nullable: true
                }
            }
        }
    ]
} as const;

export const UnitSchema = {
    allOf: [
        {
            '$ref': '#/components/schemas/BaseModel'
        },
        {
            type: 'object',
            additionalProperties: false,
            properties: {
                name: {
                    type: 'string',
                    nullable: true
                },
                abbrevation: {
                    type: 'string',
                    nullable: true
                }
            }
        }
    ]
} as const;

export const ValueSchema = {
    allOf: [
        {
            '$ref': '#/components/schemas/BaseModel'
        },
        {
            type: 'object',
            additionalProperties: false,
            properties: {
                nominal: {
                    type: 'integer',
                    format: 'int32'
                }
            }
        }
    ]
} as const;