version: "3.7"
volumes:
    sourcecode: #

services: 
    alpine: 
        image: alpine
        tty: true       
        stdin_open: true
        volumes:
        - type: volume
          source: sourcecode
          target: /home/ah/personalProject/planerp/api/Util/
        

